export default [
  {
    id: 290,
    commandName: 'IF条件',
    groupId: 7,
    parentId: 256,
    sort: 2,
    iconName: '5d1e70b9-caf0-4a49-882b-6b8ba58d7132.png',
    jsonPropertiesPane:
      '[{"component":"Group","display":"group","name":"setgroup","title":"输入","items":[{"name":"condition","title":"判断条件","component":"Condition","display":"block","initText":"设置IF条件","editedText":"修改IF条件","required":true}]}]',
    commandDesc: '当满足单个或多个条件时，执行操作，作为条件判断的开始标记',
    helpDoc: null,
    commandType: 'ifelse',
    addonProps: '{"nodeType":"feature"}',
    lastNode: 1,
    groupType: 0,
    commandVersion: 'stable',
    commandSort: 1,
    isCollect: null,
    isShow: 1,
    parentName: null,
    commandCapability: 1
  },
  {
    id: 343,
    commandName: '点击元素',
    groupId: 4,
    parentId: 253,
    sort: 4,
    iconName: '126a39db-c912-41e8-b5e6-24cabaf4199e.png',
    jsonPropertiesPane:
      '[\r\n  {\r\n    "component": "Group",\r\n    "name": "setgroup",\r\n    "display": "group",\r\n    "title": "输入",\r\n    "items": [\r\n      {\r\n        "name": "openPage",\r\n        "title": "已打开的浏览器对象",\r\n        "acceptType": ["WebPage"],\r\n        "editType": ["variable"],\r\n        "component": "VariationInput",\r\n        "display": "block",\r\n        "required": true\r\n      },\r\n      {\r\n        "name": "element",\r\n        "title": "目标元素",\r\n        "component": "ComponentInput",\r\n        "display": "block",\r\n        "acceptType": ["Control"],\r\n        "required": true\r\n      },\r\n      {\r\n        "name": "clickType",\r\n        "title": "点击方式",\r\n        "component": "Radio.Group",\r\n        "display": "block",\r\n        "required": true,\r\n        "initialValue": "left_once",\r\n        "dataSource": [\r\n          {\r\n            "value": "left_once",\r\n            "label": "左键单击"\r\n          },\r\n          {\r\n            "value": "left_twice",\r\n            "label": "左键双击"\r\n          },\r\n          {\r\n            "value": "right_once",\r\n            "label": "右键单击"\r\n          }\r\n        ]\r\n      },\r\n      {\r\n        "name": "simulate",\r\n        "title": "模拟点击",\r\n        "component": "Radio.Group",\r\n        "display": "block",\r\n        "required": true,\r\n        "initialValue": "False",\r\n        "dataSource": [\r\n          {\r\n            "value": "True",\r\n            "label": "是"\r\n          },\r\n          {\r\n            "value": "False",\r\n            "label": "否"\r\n          }\r\n        ]\r\n      },\r\n      {\r\n        "name": "clickPosition",\r\n        "title": "鼠标点击位置",\r\n        "component": "Radio.Group",\r\n        "display": "block",\r\n        "required": true,\r\n        "initialValue": "center",\r\n        "dataSource": [\r\n          {\r\n            "value": "center",\r\n            "label": "中心点"\r\n          },\r\n          {\r\n            "value": "random",\r\n            "label": "随机位置"\r\n          },\r\n          {\r\n            "value": "custom",\r\n            "label": "自定义"\r\n          }\r\n        ],\r\n        "reactions": {\r\n          "dependencies": ["simulate"],\r\n          "fulfill": {\r\n            "state": {\r\n              "visible": "{{$deps[0] ===\\"True\\"}}"\r\n            }\r\n          }\r\n        }\r\n      },\r\n      {\r\n        "name": "offsetX",\r\n        "title": "横向偏移",\r\n        "component": "VariationInput",\r\n        "initialValue": 0,\r\n        "display": "block",\r\n        "acceptType": ["Number"],\r\n        "required": "fieldNumber",\r\n        "editType": ["number", "variable"],\r\n        "reactions": {\r\n          "dependencies": ["clickPosition"],\r\n          "fulfill": {\r\n            "state": {\r\n              "visible": "{{$deps[0] ===\\"custom\\"}}"\r\n            }\r\n          }\r\n        }\r\n      },\r\n      {\r\n        "name": "offsetY",\r\n        "title": "纵向偏移",\r\n        "component": "VariationInput",\r\n        "initialValue": 0,\r\n        "display": "block",\r\n        "acceptType": ["Number"],\r\n        "required": "fieldNumber",\r\n        "editType": ["number", "variable"],\r\n        "reactions": {\r\n          "dependencies": ["clickPosition"],\r\n          "fulfill": {\r\n            "state": {\r\n              "visible": "{{$deps[0] ===\\"custom\\"}}"\r\n            }\r\n          }\r\n        }\r\n      }\r\n    ]\r\n  },\r\n  {\r\n    "component": "FormCollapse",\r\n    "name": "senior",\r\n    "display": "group",\r\n    "title": "高级选项",\r\n    "items": [\r\n      {\r\n        "name": "ctrlIndex",\r\n        "title": "元素索引",\r\n        "component": "VariationInput",\r\n        "initialValue": 1,\r\n        "acceptType": ["Number"],\r\n        "display": "block",\r\n        "required": "fieldNumber",\r\n        "editType": ["number", "variable", "express"],\r\n        "reactions": {\r\n          "dependencies": ["element"],\r\n          "fulfill": {\r\n            "state": {\r\n              "hidden": "{{!!($deps[0] && $deps[0].control_index)}}"\r\n            }\r\n          }\r\n        }\r\n      },\r\n      {\r\n        "name": "timeout",\r\n        "title": "单次执行超时时间（秒）",\r\n        "component": "VariationInput",\r\n        "initialValue": 10,\r\n        "acceptType": ["Number"],\r\n        "display": "block",\r\n        "required": "fieldNumber",\r\n        "editType": ["number", "variable", "express"]\r\n      },\r\n      {\r\n        "name": "gs_pre_timeout",\r\n        "title": "执行前延迟（秒）",\r\n        "component": "VariationInput",\r\n        "initialValue": 0,\r\n        "display": "block",\r\n        "acceptType": ["Number"],\r\n        "editType": ["number", "variable", "express"]\r\n      },\r\n      {\r\n        "name": "gs_lat_timeout",\r\n        "title": "执行后延迟（秒）",\r\n        "component": "VariationInput",\r\n        "initialValue": 0,\r\n        "acceptType": ["Number"],\r\n        "editType": ["number", "variable", "express"],\r\n        "display": "block"\r\n      },\r\n      {\r\n        "name": "generalSettings",\r\n        "title": "执行失败后的动作",\r\n        "component": "Checkbox.Group",\r\n        "display": "block",\r\n        "dataSource": [\r\n          {\r\n            "label": "记录日志",\r\n            "value": "log",\r\n            "disabled": true\r\n          },\r\n          {\r\n            "label": "退出",\r\n            "value": "exit",\r\n            "disabled": false\r\n          },\r\n          {\r\n            "label": "弹出提醒",\r\n            "value": "msgbox",\r\n            "disabled": false\r\n          }\r\n        ],\r\n        "initialValue": ["log", "exit"]\r\n      }\r\n    ]\r\n  }\r\n]\r\n',
    commandDesc: '点击目标网页中的指定元素',
    helpDoc: null,
    commandType: 'belementclick',
    addonProps: '{"nodeType":"feature"}',
    lastNode: 1,
    groupType: 0,
    commandVersion: 'stable',
    commandSort: 1,
    isCollect: null,
    isShow: 1,
    parentName: null,
    commandCapability: 1
  },
  {
    id: 284,
    commandName: '按照次数循环',
    groupId: 7,
    parentId: 256,
    sort: 5,
    iconName: '5ac25aaa-04b1-431e-ab14-03b66c2e02d2.png',
    jsonPropertiesPane:
      '[{"component":"Group","display":"group","name":"setgroup","title":"输入","items":[{"title":"循环起始值","name":"startNum","initialValue":1,"component":"VariationInput","display":"block","acceptType":["Number"],"required":"fieldNumber","editType":["number","variable","express"]},{"title":"循环结束值","name":"endNum","initialValue":1,"component":"VariationInput","display":"block","acceptType":["Number"],"required":"fieldNumber","editType":["number","variable","express"]},{"title":"步长值","name":"stepLenth","component":"VariationInput","initialValue":1,"display":"block","acceptType":["Number"],"required":"fieldNumber","editType":["number","variable","express"]}]},{"component":"Group","display":"group","name":"outgroup","title":"输出","items":[{"name":"output_i","title":"每次循环项","tips":"支持小写字母及 _ ， 例如：a 或 a_b 或 _c。输出后，仅可在循环体内引用","placeholder":"使用变量名称接收该循环项","component":"VariationInput","display":"block","autoName":"range_item","editType":["variable"],"returnType":"Number","acceptType":["Number"]}]}]',
    commandDesc: '对一组指令进行指定次数的循环操作',
    helpDoc: null,
    commandType: 'loop_times',
    addonProps: '{"nodeType":"feature"}',
    lastNode: 1,
    groupType: 0,
    commandVersion: 'stable',
    commandSort: 1,
    isCollect: null,
    isShow: 1,
    parentName: null,
    commandCapability: 1
  },
  {
    id: 269,
    commandName: '获取已打开网页',
    groupId: 4,
    parentId: 253,
    sort: 2,
    iconName: '81d356b7-7285-44b2-bfc6-e9868b2af1fe.png',
    jsonPropertiesPane:
      '[\n  {\n    "component": "Group",\n    "display": "group",\n    "name": "setgroup",\n    "title": "输入",\n    "items": [\n      {\n        "name": "type",\n        "title": "浏览器类型",\n        "component": "Radio.Group",\n        "display": "block",\n        "initialValue": "chrome",\n        "required": true,\n        "dataSource": [\n          {\n            "value": "chrome",\n            "label": "Google Chrome"\n          },\n          {\n            "value": "ie",\n            "label": "IE"\n          }\n        ]\n      },\n      {\n        "name": "mode",\n        "title": "查找位置",\n        "component": "Radio.Group",\n        "display": "block",\n        "initialValue": "title",\n        "required": true,\n        "dataSource": [\n          {\n            "value": "title",\n            "label": "标题"\n          },\n          {\n            "value": "url",\n            "label": "网址"\n          }\n        ]\n      },\n      {\n        "name": "content",\n        "title": "查找内容",\n        "component": "VariationInput",\n        "display": "block",\n        "acceptType": [\n          "String"\n        ],\n        "required": true,\n        "editType": [\n          "text",\n          "variable",\n          "express"\n        ]\n      },\n      {\n        "name": "rule",\n        "title": "查找规则",\n        "component": "Radio.Group",\n        "display": "block",\n        "initialValue": "equal",\n        "required": true,\n        "dataSource": [\n          {\n            "value": "equal",\n            "label": "等于"\n          },\n          {\n            "value": "contain",\n            "label": "包含"\n          }\n        ]\n      },\n      {\n        "name": "isOpenNewWeb",\n        "title": "获取失败时打开新网页",\n        "component": "Radio.Group",\n        "display": "block",\n        "initialValue": false,\n        "dataSource": [\n          {\n            "value": true,\n            "label": "是"\n          },\n          {\n            "value": false,\n            "label": "否"\n          }\n        ],\n        "reactions": {\n          "target": "newWebUrl",\n          "fulfill": {\n            "state": {\n              "visible": "{{$self.value === true}}"\n            }\n          }\n        }\n      },\n      {\n        "name": "newWebUrl",\n        "title": "新网页",\n        "component": "VariationInput",\n        "display": "block",\n        "editType": [\n          "text",\n          "variable",\n          "express"\n        ],\n        "acceptType": [\n          "String"\n        ]\n      }\n    ]\n  },\n  {\n    "component": "FormCollapse",\n    "name": "senior",\n    "display": "group",\n    "title": "高级选项",\n    "items": [\n      {\n        "name": "gs_pre_timeout",\n        "title": "执行前延迟（秒）",\n        "component": "VariationInput",\n        "initialValue": 0,\n        "acceptType": [\n          "Number"\n        ],\n        "editType": [\n          "number",\n          "variable",\n          "express"\n        ],\n        "display": "block"\n      },\n      {\n        "name": "gs_lat_timeout",\n        "title": "执行后延迟（秒）",\n        "component": "VariationInput",\n        "initialValue": 0,\n        "acceptType": [\n          "Number"\n        ],\n        "editType": [\n          "number",\n          "variable",\n          "express"\n        ],\n        "display": "block"\n      },\n      {\n        "name": "generalSettings",\n        "title": "执行失败后的动作",\n        "component": "Checkbox.Group",\n        "display": "block",\n        "dataSource": [\n          {\n            "label": "记录日志",\n            "value": "log",\n            "disabled": true\n          },\n          {\n            "label": "退出",\n            "value": "exit",\n            "disabled": false\n          },\n          {\n            "label": "弹出提醒",\n            "value": "msgbox",\n            "disabled": false\n          }\n        ],\n        "initialValue": [\n          "log",\n          "exit"\n        ]\n      }\n    ]\n  },\n  {\n    "component": "Group",\n    "name": "outgroup",\n    "display": "group",\n    "title": "输出",\n    "items": [\n      {\n        "name": "output_page",\n        "title": "浏览器对象",\n        "placeholder": "使用变量名称接收该浏览器对象",\n        "component": "VariationInput",\n        "display": "block",\n        "required": true,\n        "autoName": "web_obj",\n        "editType": [\n          "variable"\n        ],\n        "returnType": "WebPage",\n        "acceptType": [\n          "WebPage"\n        ]\n      }\n    ]\n  }\n]',
    commandDesc: '根据标题或者网址获取已打开的网页，常作为网页操作的前置指令',
    helpDoc: null,
    commandType: 'bgetopen',
    addonProps: '{"nodeType":"feature"}',
    lastNode: 1,
    groupType: 0,
    commandVersion: 'stable',
    commandSort: 1,
    isCollect: null,
    isShow: 1,
    parentName: null,
    commandCapability: 1
  },
  {
    id: 335,
    commandName: '获取文本',
    groupId: 4,
    parentId: 253,
    sort: 5,
    iconName: '4523b97f-5270-4240-9245-7eeff189d745.png',
    jsonPropertiesPane:
      '[{"component":"Group","display":"group","title":"输入","name":"setgroup","items":[{"name":"page","title":"已打开的浏览器对象","component":"VariationInput","display":"block","editType":["variable"],"acceptType":["WebPage"],"required":true},{"name":"ctrl","title":"目标元素","component":"ComponentInput","acceptType":["Control"],"display":"block","required":true}]},{"component":"FormCollapse","name":"senior","display":"group","title":"高级选项","items":[{"name":"ctrlIndex","title":"元素索引","initialValue":1,"component":"VariationInput","display":"block","acceptType":["Number"],"required":"fieldNumber","editType":["number","variable","express"],"reactions":{"dependencies":["ctrl"],"fulfill":{"state":{"hidden":"{{!!($deps[0] && $deps[0].control_index)}}"}}}},{"name":"timeout","title":"单次执行超过时间（秒）","component":"VariationInput","initialValue":10,"display":"block","acceptType":["Number"],"required":"fieldNumber","editType":["number","variable","express"]},{"name":"gs_pre_timeout","title":"执行前延迟（秒）","component":"VariationInput","initialValue":0,"display":"block","acceptType":["Number"],"editType":["number","variable","express"]},{"name":"gs_lat_timeout","title":"执行后延迟（秒）","component":"VariationInput","initialValue":0,"acceptType":["Number"],"editType":["number","variable","express"],"display":"block"},{"name":"generalSettings","title":"执行失败后的动作","component":"Checkbox.Group","display":"block","dataSource":[{"label":"记录日志","value":"log","disabled":true},{"label":"退出","value":"exit","disabled":false},{"label":"弹出提醒","value":"msgbox","disabled":false}],"initialValue":["log","exit"]}]},{"component":"Group","name":"outgroup","display":"group","title":"输出","items":[{"name":"output_text","title":"获取到的文本","placeholder":"使用变量名称接收获取到的文本","component":"VariationInput","autoName":"web_text","editType":["variable"],"acceptType":["String"],"returnType":"String","display":"block"}]}]',
    commandDesc: '获取目标网页元素的文本内容',
    helpDoc: null,
    commandType: 'bugettext',
    addonProps: '{"nodeType":"feature"}',
    lastNode: 1,
    groupType: 0,
    commandVersion: 'stable',
    commandSort: 1,
    isCollect: null,
    isShow: 1,
    parentName: null,
    commandCapability: 1
  }
]
