# https://github.com/imbatony/electorn-chinese-chess

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

name: 发布 Release

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build Release & Upload Assets
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true

      - name: Use tag
        run: echo ${{ steps.tag.outputs.tag }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            /*.html
            cart/*.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
