# https://github.com/imbatony/electorn-chinese-chess

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

name: 发布 Release

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build Release & Upload Assets
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            a_vscode-extension/src/*.ts
